const builtin = @import("builtin");
const std = @import("std");
const Context = @import("context.zig").Context;
const cli_registry = @import("command_registry.zig");
const scaffold = @import("scaffold.zig");
const core = @import("../core/mod.zig");
const project_mod = @import("../core/project.zig");
const build = @import("../build/mod.zig");
const package = @import("../package/mod.zig");
const source_spec = @import("../package/source_spec.zig");
const translate = @import("../translate/mod.zig");
const graph = @import("../graph/mod.zig");
const version = @import("../version.zig");
const testing = std.testing;

const ProjectPathValidationError = error{
    EmptyPath,
    AbsolutePath,
    TraversalSegment,
    CurrentDirectorySegment,
};

const NoArgCommandValidationError = error{UnexpectedArguments};

fn validateNoArgs(command_args: []const []const u8) NoArgCommandValidationError!void {
    if (command_args.len != 0) return error.UnexpectedArguments;
}

fn ensureNoArgs(ctx: *Context, command_name: []const u8, command_args: []const []const u8) !void {
    validateNoArgs(command_args) catch {
        try ctx.printErr("error: {s} does not take positional arguments\n", .{command_name});
        return error.UnexpectedArguments;
    };
}

pub fn handleVersion(ctx: *Context) !u8 {
    try ctx.print("ovo {s}\n", .{version.string});
    return 0;
}

pub fn handleNew(ctx: *Context, command_args: []const []const u8) !u8 {
    if (command_args.len == 0) {
        try ctx.printErr("error: missing project name\n", .{});
        return 2;
    }
    if (command_args.len != 1) {
        try ctx.printErr("error: new takes exactly one project path argument\n", .{});
        return 2;
    }

    const root_path = command_args[0];
    validateNewProjectPath(root_path) catch |err| {
        switch (err) {
            error.EmptyPath => try ctx.printErr("error: project path cannot be empty\n", .{}),
            error.AbsolutePath => try ctx.printErr("error: project path must be relative\n", .{}),
            error.TraversalSegment => try ctx.printErr("error: project path cannot contain '..' segments\n", .{}),
            error.CurrentDirectorySegment => try ctx.printErr("error: project path cannot contain '.' segments\n", .{}),
        }
        return 2;
    };

    const project_name = projectDisplayNameFromPath(root_path);
    const target_base_id = try normalizeTargetBaseId(ctx.allocator, project_name);
    try scaffold.createProjectSkeleton(ctx.allocator, root_path, project_name, target_base_id);
    try core.fs.writeFile(
        try std.fmt.allocPrint(ctx.allocator, "{s}/README.md", .{root_path}),
        "Generated by OVO\n",
    );
    try ctx.print("new: created project '{s}'\n", .{root_path});
    return 0;
}

pub fn handleInit(ctx: *Context, command_args: []const []const u8) !u8 {
    if (command_args.len != 0) {
        try ctx.printErr("error: init does not take positional arguments\n", .{});
        return 2;
    }

    const cwd_name = projectNameFromCwd(ctx.allocator);
    const target_base_id = try normalizeTargetBaseId(ctx.allocator, cwd_name);
    try scaffold.createProjectSkeleton(ctx.allocator, ".", cwd_name, target_base_id);
    try ctx.print("init: wrote build.zon and starter C++ layout for '{s}'\n", .{cwd_name});
    return 0;
}

pub fn handleBuild(ctx: *Context, command_args: []const []const u8, _: []const []const u8) !u8 {
    var force = false;
    var target_name: ?[]const u8 = null;
    var jobs: u32 = 0;

    var i: usize = 0;
    while (i < command_args.len) : (i += 1) {
        const arg = command_args[i];
        if (std.mem.eql(u8, arg, "--force")) {
            force = true;
        } else if (std.mem.eql(u8, arg, "-j") or std.mem.eql(u8, arg, "--jobs")) {
            i += 1;
            if (i >= command_args.len) {
                try ctx.printErr("error: {s} requires a job count\n", .{arg});
                return 2;
            }
            jobs = std.fmt.parseInt(u32, command_args[i], 10) catch {
                try ctx.printErr("error: invalid job count '{s}'\n", .{command_args[i]});
                return 2;
            };
            if (jobs == 0) {
                try ctx.printErr("error: job count must be >= 1\n", .{});
                return 2;
            }
        } else if (std.mem.startsWith(u8, arg, "--jobs=")) {
            jobs = std.fmt.parseInt(u32, arg["--jobs=".len..], 10) catch {
                try ctx.printErr("error: invalid --jobs value '{s}'\n", .{arg["--jobs=".len..]});
                return 2;
            };
            if (jobs == 0) {
                try ctx.printErr("error: job count must be >= 1\n", .{});
                return 2;
            }
        } else if (std.mem.startsWith(u8, arg, "-j")) {
            jobs = std.fmt.parseInt(u32, arg[2..], 10) catch {
                try ctx.printErr("error: invalid -j value '{s}'\n", .{arg[2..]});
                return 2;
            };
            if (jobs == 0) {
                try ctx.printErr("error: job count must be >= 1\n", .{});
                return 2;
            }
        } else if (std.mem.startsWith(u8, arg, "--")) {
            try ctx.printErr("error: unknown build flag '{s}'\n", .{arg});
            return 2;
        } else if (target_name == null) {
            target_name = arg;
        } else {
            try ctx.printErr("error: build accepts at most one target argument\n", .{});
            return 2;
        }
    }
    const result = try build.orchestrator.buildProject(ctx.allocator, .{
        .target_name = target_name,
        .optimize_override = ctx.profile,
        .force = force,
        .jobs = jobs,
        .quiet = ctx.quiet,
    });
    try ctx.print("build: project={s}\n", .{result.project_name});
    for (result.artifacts) |artifact| {
        try ctx.print("  built {s} -> {s}\n", .{ artifact.name, artifact.path });
    }
    return 0;
}

pub fn handleRun(ctx: *Context, command_args: []const []const u8, passthrough_args: []const []const u8) !u8 {
    if (command_args.len > 1) {
        try ctx.printErr("error: run accepts at most one target argument before '--'\n", .{});
        return 2;
    }

    var requested_target = if (command_args.len > 0) command_args[0] else null;
    if (requested_target == null) {
        const project = try build.orchestrator.loadProject(ctx.allocator);
        const target = build.orchestrator.defaultRunnableTarget(project) orelse {
            try ctx.printErr("error: no executable or test target available\n", .{});
            return 2;
        };
        requested_target = target.name;
    }

    const result = try build.orchestrator.buildProject(ctx.allocator, .{
        .target_name = requested_target,
        .optimize_override = ctx.profile,
    });
    const artifact = build.orchestrator.findRunnableArtifact(result, requested_target) orelse {
        try ctx.printErr("error: no runnable executable target found\n", .{});
        return 2;
    };

    var argv: std.ArrayList([]const u8) = .empty;
    try argv.append(ctx.allocator, artifact.path);
    for (passthrough_args) |arg| try argv.append(ctx.allocator, arg);
    const code = try core.exec.runInherit(argv.items);
    return code;
}

pub fn handleTest(ctx: *Context, command_args: []const []const u8, _: []const []const u8) !u8 {
    if (command_args.len > 1) {
        try ctx.printErr("error: test accepts at most one pattern argument\n", .{});
        return 2;
    }

    const pattern = if (command_args.len > 0) command_args[0] else null;
    const result = try build.orchestrator.buildProject(ctx.allocator, .{
        .target_pattern = pattern,
        .optimize_override = ctx.profile,
        .test_only = true,
    });

    for (result.artifacts) |artifact| {
        var argv: std.ArrayList([]const u8) = .empty;
        try argv.append(ctx.allocator, artifact.path);
        const code = try core.exec.runInherit(argv.items);
        if (code != 0) return code;
    }
    try ctx.print("test: executed {d} test target(s)\n", .{result.artifacts.len});
    return 0;
}

pub fn handleClean(ctx: *Context, command_args: []const []const u8) !u8 {
    ensureNoArgs(ctx, "clean", command_args) catch return 2;
    try core.fs.removeTreeIfExists(".ovo");
    try core.fs.deleteFileIfExists("ovo.lock.zon");
    try ctx.print("clean: removed .ovo and transient lock artifacts\n", .{});
    return 0;
}

pub fn handleInstall(ctx: *Context, command_args: []const []const u8) !u8 {
    ensureNoArgs(ctx, "install", command_args) catch return 2;
    const result = try build.orchestrator.buildProject(ctx.allocator, .{
        .optimize_override = ctx.profile,
    });
    try core.fs.ensureDir(".ovo/install/bin");
    try core.fs.ensureDir(".ovo/install/lib");

    for (result.artifacts) |artifact| {
        const file_name = std.fs.path.basename(artifact.path);
        const install_path = switch (artifact.kind) {
            .executable, .test_target => try std.fmt.allocPrint(ctx.allocator, ".ovo/install/bin/{s}", .{file_name}),
            .library_static, .library_shared => try std.fmt.allocPrint(ctx.allocator, ".ovo/install/lib/{s}", .{file_name}),
        };
        defer ctx.allocator.free(install_path);

        try core.fs.copyFile(ctx.allocator, artifact.path, install_path);
        try ctx.print("install: {s}\n", .{install_path});
    }
    return 0;
}

pub fn handleAdd(ctx: *Context, command_args: []const []const u8) !u8 {
    const parsed = parseAddCommandArgs(command_args) catch |err| {
        switch (err) {
            error.MissingPackageName => {
                try ctx.printErr("error: missing package name\n", .{});
            },
            error.MissingSourceValue => {
                try ctx.printErr("error: missing value for source flag\n", .{});
            },
            error.UnknownFlag => {
                try ctx.printErr("error: unknown add flag\n", .{});
            },
            error.MutuallyExclusiveSourceFlags => {
                try ctx.printErr("error: mutually exclusive source flags are not allowed\n", .{});
            },
            error.SourceAndPositionalVersion => {
                try ctx.printErr("error: source flag cannot be combined with positional version_str\n", .{});
            },
            error.TooManyArguments => {
                try ctx.printErr("error: too many arguments for add\n", .{});
            },
        }
        return 2;
    };

    var manager = package.manager.PackageManager.init(ctx.allocator);
    try manager.addWithSource(parsed.package_name, parsed.version_str, parsed.source);
    if (parsed.version_str) |v| {
        try ctx.print("add: {s} {s}\n", .{ parsed.package_name, v });
    } else {
        try ctx.print("add: {s}\n", .{parsed.package_name});
    }
    return 0;
}

pub fn handleRemove(ctx: *Context, command_args: []const []const u8) !u8 {
    if (command_args.len == 0) {
        try ctx.printErr("error: missing package name\n", .{});
        return 2;
    }
    if (command_args.len > 1) {
        try ctx.printErr("error: remove takes exactly one package name\n", .{});
        return 2;
    }
    var manager = package.manager.PackageManager.init(ctx.allocator);
    try manager.remove(command_args[0]);
    try ctx.print("remove: {s}\n", .{command_args[0]});
    return 0;
}

pub fn handleFetch(ctx: *Context, command_args: []const []const u8) !u8 {
    var refresh = false;
    for (command_args) |arg| {
        if (std.mem.eql(u8, arg, "--refresh")) {
            refresh = true;
            continue;
        }
        if (std.mem.startsWith(u8, arg, "--")) {
            try ctx.printErr("error: unknown fetch flag '{s}'\n", .{arg});
            return 2;
        }
        try ctx.printErr("error: fetch does not take positional arguments\n", .{});
        return 2;
    }
    const project = try build.orchestrator.loadProject(ctx.allocator);
    var manager = package.manager.PackageManager.init(ctx.allocator);
    try manager.fetch(refresh);
    try ctx.print("fetch: dependency cache refreshed ({d} deps)\n", .{project.dependencies.len});
    return 0;
}

pub fn handleUpdate(ctx: *Context, command_args: []const []const u8) !u8 {
    if (command_args.len > 1) {
        try ctx.printErr("error: update accepts at most one dependency name\n", .{});
        return 2;
    }

    var manager = package.manager.PackageManager.init(ctx.allocator);
    const dep = if (command_args.len > 0) command_args[0] else null;
    try manager.update(dep);
    if (dep) |name| {
        try ctx.print("update: dependency {s} updated\n", .{name});
    } else {
        try ctx.print("update: dependencies updated\n", .{});
    }
    return 0;
}

pub fn handleLock(ctx: *Context, command_args: []const []const u8) !u8 {
    ensureNoArgs(ctx, "lock", command_args) catch return 2;
    var manager = package.manager.PackageManager.init(ctx.allocator);
    try manager.lock();
    try ctx.print("lock: wrote ovo.lock.zon\n", .{});
    return 0;
}

const ParsedAddArgs = struct {
    package_name: []const u8,
    version_str: ?[]const u8,
    source: ?source_spec.SourceKind,
};

const AddParseError = error{
    MissingPackageName,
    MissingSourceValue,
    UnknownFlag,
    MutuallyExclusiveSourceFlags,
    SourceAndPositionalVersion,
    TooManyArguments,
};

fn parseAddCommandArgs(command_args: []const []const u8) AddParseError!ParsedAddArgs {
    if (command_args.len == 0) return AddParseError.MissingPackageName;

    var package_name: ?[]const u8 = null;
    var version_str: ?[]const u8 = null;
    var source: ?source_spec.SourceKind = null;

    var i: usize = 0;
    while (i < command_args.len) : (i += 1) {
        const arg = command_args[i];

        if (std.mem.startsWith(u8, arg, "--git=")) {
            if (source != null) return AddParseError.MutuallyExclusiveSourceFlags;
            const value = arg["--git=".len..];
            if (value.len == 0) return AddParseError.MissingSourceValue;
            if (version_str != null) return AddParseError.SourceAndPositionalVersion;
            source = .git;
            version_str = value;
            continue;
        }
        if (std.mem.startsWith(u8, arg, "--path=")) {
            if (source != null) return AddParseError.MutuallyExclusiveSourceFlags;
            const value = arg["--path=".len..];
            if (value.len == 0) return AddParseError.MissingSourceValue;
            if (version_str != null) return AddParseError.SourceAndPositionalVersion;
            source = .local;
            version_str = value;
            continue;
        }
        if (std.mem.startsWith(u8, arg, "--registry=")) {
            if (source != null) return AddParseError.MutuallyExclusiveSourceFlags;
            const value = arg["--registry=".len..];
            if (value.len == 0) return AddParseError.MissingSourceValue;
            if (version_str != null) return AddParseError.SourceAndPositionalVersion;
            source = .registry;
            version_str = value;
            continue;
        }
        if (std.mem.eql(u8, arg, "--git")) {
            if (source != null) return AddParseError.MutuallyExclusiveSourceFlags;
            if (i + 1 >= command_args.len) return AddParseError.MissingSourceValue;
            const value = command_args[i + 1];
            if (value.len == 0) return AddParseError.MissingSourceValue;
            if (version_str != null) return AddParseError.SourceAndPositionalVersion;
            source = .git;
            version_str = value;
            i += 1;
            continue;
        }
        if (std.mem.eql(u8, arg, "--path")) {
            if (source != null) return AddParseError.MutuallyExclusiveSourceFlags;
            if (i + 1 >= command_args.len) return AddParseError.MissingSourceValue;
            const value = command_args[i + 1];
            if (value.len == 0) return AddParseError.MissingSourceValue;
            if (version_str != null) return AddParseError.SourceAndPositionalVersion;
            source = .local;
            version_str = value;
            i += 1;
            continue;
        }
        if (std.mem.eql(u8, arg, "--registry")) {
            if (source != null) return AddParseError.MutuallyExclusiveSourceFlags;
            if (i + 1 >= command_args.len) return AddParseError.MissingSourceValue;
            const value = command_args[i + 1];
            if (value.len == 0) return AddParseError.MissingSourceValue;
            if (version_str != null) return AddParseError.SourceAndPositionalVersion;
            source = .registry;
            version_str = value;
            i += 1;
            continue;
        }

        if (std.mem.startsWith(u8, arg, "--")) return AddParseError.UnknownFlag;

        if (package_name == null) {
            package_name = arg;
            continue;
        }
        if (source == null and version_str == null) {
            version_str = arg;
            continue;
        }
        return AddParseError.TooManyArguments;
    }

    if (package_name == null) return AddParseError.MissingPackageName;
    return .{
        .package_name = package_name.?,
        .version_str = version_str,
        .source = source,
    };
}

test "add argument parser supports source flags and rejects conflicts" {
    const parsed = try parseAddCommandArgs(&.{ "pkg", "1.2.3", "--git", "https://example.com/a.git" });
    try testing.expectError(AddParseError.SourceAndPositionalVersion, parseAddCommandArgs(&.{ "pkg", "1.2.3", "--git=https://example.com/a.git" }));
    try testing.expectError(AddParseError.MutuallyExclusiveSourceFlags, parseAddCommandArgs(&.{ "pkg", "--git", "https://example.com/a.git", "--path", "./local" }));
    try testing.expectError(AddParseError.MutuallyExclusiveSourceFlags, parseAddCommandArgs(&.{ "pkg", "--git=https://example.com/a.git", "--registry=latest" }));
    try testing.expectError(AddParseError.MissingSourceValue, parseAddCommandArgs(&.{ "pkg", "--path" }));
    try testing.expectError(AddParseError.UnknownFlag, parseAddCommandArgs(&.{ "pkg", "--bad" }));
    try testing.expectEqual(@as(?[]const u8, "1.2.3"), parsed.version_str);
    try testing.expectEqual(source_spec.SourceKind.local, (try parseAddCommandArgs(&.{ "pkg", "--path", "./local" })).source.?);
}

test "new project path validation enforces safe relative input" {
    try validateNewProjectPath("myapp");
    try validateNewProjectPath("apps/my app");
    try validateNewProjectPath("apps\\my app");

    try testing.expectError(ProjectPathValidationError.EmptyPath, validateNewProjectPath(""));
    try testing.expectError(ProjectPathValidationError.AbsolutePath, validateNewProjectPath("/tmp/myapp"));
    try testing.expectError(ProjectPathValidationError.TraversalSegment, validateNewProjectPath("../myapp"));
    try testing.expectError(ProjectPathValidationError.TraversalSegment, validateNewProjectPath("apps/../myapp"));
    try testing.expectError(ProjectPathValidationError.CurrentDirectorySegment, validateNewProjectPath("."));
    try testing.expectError(ProjectPathValidationError.CurrentDirectorySegment, validateNewProjectPath("apps/./myapp"));
}

test "project name helpers derive deterministic scaffold metadata" {
    try testing.expectEqualStrings("my app", projectDisplayNameFromPath("apps/my app"));
    try testing.expectEqualStrings("app", projectDisplayNameFromPath("/"));

    const normalized_space = try normalizeTargetBaseId(testing.allocator, "my app");
    defer testing.allocator.free(normalized_space);
    try testing.expectEqualStrings("my_app", normalized_space);

    const normalized_numeric = try normalizeTargetBaseId(testing.allocator, "123 project");
    defer testing.allocator.free(normalized_numeric);
    try testing.expectEqualStrings("app_123_project", normalized_numeric);

    const normalized_symbols = try normalizeTargetBaseId(testing.allocator, "%%%");
    defer testing.allocator.free(normalized_symbols);
    try testing.expectEqualStrings("app", normalized_symbols);
}

test "selected CLI handlers reject extra positional arguments" {
    var ctx = Context{
        .allocator = testing.allocator,
        .quiet = true,
        .suppress_stderr = true,
    };

    try testing.expectEqual(@as(u8, 2), try handleBuild(&ctx, &.{ "app", "extra" }, &.{}));
    try testing.expectEqual(@as(u8, 2), try handleRun(&ctx, &.{ "app", "extra" }, &.{}));
    try testing.expectEqual(@as(u8, 2), try handleTest(&ctx, &.{ "unit", "extra" }, &.{}));
    try testing.expectEqual(@as(u8, 2), try handleRemove(&ctx, &.{ "fmt", "extra" }));
    try testing.expectEqual(@as(u8, 2), try handleUpdate(&ctx, &.{ "fmt", "extra" }));
    try testing.expectEqual(@as(u8, 2), try handleDoc(&ctx, &.{"extra"}));
    try testing.expectEqual(@as(u8, 2), try handleDoctor(&ctx, &.{"extra"}));
    try testing.expectEqual(@as(u8, 2), try handleInfo(&ctx, &.{"extra"}));
}

pub fn handleDeps(ctx: *Context, command_args: []const []const u8) !u8 {
    ensureNoArgs(ctx, "deps", command_args) catch return 2;
    var manager = package.manager.PackageManager.init(ctx.allocator);
    const summary = try manager.dependencySummary();
    try ctx.print("{s}\n", .{summary});
    return 0;
}

pub fn handleDoc(ctx: *Context, command_args: []const []const u8) !u8 {
    ensureNoArgs(ctx, "doc", command_args) catch return 2;

    const project = try build.orchestrator.loadProject(ctx.allocator);
    try core.fs.ensureDir("docs");
    var output: std.ArrayList(u8) = .empty;

    try output.print(ctx.allocator, "# {s}\n\n", .{project.name});
    try output.print(ctx.allocator, "- Version: `{s}`\n", .{project.version});
    try output.print(ctx.allocator, "- License: `{s}`\n", .{project.license orelse "n/a"});
    try output.print(ctx.allocator, "- Targets: `{d}`\n", .{project.targets.len});
    try output.print(ctx.allocator, "- Dependencies: `{d}`\n", .{project.dependencies.len});
    try output.appendSlice(ctx.allocator, "\n## Targets\n");
    for (project.targets) |target| {
        try output.print(ctx.allocator, "- `{s}` (`{s}`)\n", .{ target.name, project_mod.targetTypeLabel(target.kind) });
    }

    try core.fs.writeFile("docs/project-reference.md", output.items);

    const command_reference = try cli_registry.renderCommandReferenceMarkdown(ctx.allocator);
    defer ctx.allocator.free(command_reference);
    try core.fs.writeFile("docs/command-reference.md", command_reference);

    try ctx.print("doc: wrote docs/project-reference.md\n", .{});
    try ctx.print("doc: wrote docs/command-reference.md\n", .{});
    return 0;
}

const DoctorVersionStatus = struct {
    active_version: []const u8,
    matches_required: bool,
};

fn evaluateDoctorVersion(required_version: []const u8, captured_stdout: []const u8) DoctorVersionStatus {
    const active_version = std.mem.trim(u8, captured_stdout, " \t\r\n");
    return .{
        .active_version = active_version,
        .matches_required = std.mem.eql(u8, active_version, required_version),
    };
}

pub fn handleDoctor(ctx: *Context, command_args: []const []const u8) !u8 {
    ensureNoArgs(ctx, "doctor", command_args) catch return 2;
    const required_version_str_raw = core.fs.readFileAlloc(ctx.allocator, ".zigversion") catch null;
    defer if (required_version_str_raw) |bytes| ctx.allocator.free(bytes);
    const required_version_str: []const u8 = if (required_version_str_raw) |bytes|
        std.mem.trim(u8, bytes, " \t\r\n")
    else
        builtin.zig_version_string;
    try ctx.print("doctor: required_zig={s}\n", .{required_version_str});

    var zig_version_ok = false;
    const zig_version_result = core.exec.runCapture(ctx.allocator, &.{ "zig", "version" }) catch |err| blk: {
        try ctx.printErr("doctor: unable to run `zig version` ({s})\n", .{@errorName(err)});
        break :blk null;
    };
    if (zig_version_result) |result| {
        defer ctx.allocator.free(result.stdout);
        defer ctx.allocator.free(result.stderr);

        if (result.code != 0) {
            try ctx.printErr("doctor: `zig version` exited with code {d}\n", .{result.code});
            const stderr_text = std.mem.trim(u8, result.stderr, " \t\r\n");
            if (stderr_text.len > 0) {
                try ctx.printErr("doctor: zig stderr={s}\n", .{stderr_text});
            }
        } else {
            const status = evaluateDoctorVersion(required_version_str, result.stdout);
            try ctx.print("doctor: active_zig={s}\n", .{status.active_version});
            if (status.matches_required) {
                try ctx.print("doctor: zig_version_match ok\n", .{});
                zig_version_ok = true;
            } else {
                try ctx.printErr(
                    "doctor: zig_version_match fail (required {s}, active {s})\n",
                    .{ required_version_str, status.active_version },
                );
            }
        }
    }

    const ToolCheck = struct {
        name: []const u8,
        required: bool,
    };
    const tools = [_]ToolCheck{
        .{ .name = "zig", .required = true },
        .{ .name = "clang++", .required = false },
        .{ .name = "g++", .required = false },
        .{ .name = "cmake", .required = false },
        .{ .name = "ninja", .required = false },
        .{ .name = "clang-format", .required = false },
        .{ .name = "clang-tidy", .required = false },
        .{ .name = "doxygen", .required = false },
        .{ .name = "clang-doc", .required = false },
    };
    var missing_required: usize = 0;
    var missing_optional: usize = 0;
    for (tools) |tool| {
        const available = core.exec.commandExists(tool.name);
        if (available) {
            try ctx.print("doctor: {s} ok\n", .{tool.name});
            continue;
        }
        if (tool.required) {
            try ctx.print("doctor: {s} missing-required\n", .{tool.name});
            missing_required += 1;
        } else {
            try ctx.print("doctor: {s} missing-optional\n", .{tool.name});
            missing_optional += 1;
        }
    }
    if (missing_optional > 0) {
        try ctx.print("doctor: optional tools missing ({d}); related subcommands may use fallbacks\n", .{missing_optional});
    }
    return if (zig_version_ok and missing_required == 0) 0 else 1;
}

test "doctor version evaluation trims zig output and detects mismatches" {
    const matching = evaluateDoctorVersion("0.16.0-dev.2984+cb7d2b056", "0.16.0-dev.2984+cb7d2b056\n");
    try testing.expectEqualStrings("0.16.0-dev.2984+cb7d2b056", matching.active_version);
    try testing.expect(matching.matches_required);

    const mismatch = evaluateDoctorVersion("0.16.0-dev.2984+cb7d2b056", "0.16.0-dev.9999+deadbeef\r\n");
    try testing.expectEqualStrings("0.16.0-dev.9999+deadbeef", mismatch.active_version);
    try testing.expect(!mismatch.matches_required);
}

pub fn handleFmt(ctx: *Context, command_args: []const []const u8) !u8 {
    ensureNoArgs(ctx, "fmt", command_args) catch return 2;
    if (!core.exec.commandExists("clang-format")) {
        try ctx.printErr("error: clang-format not found in PATH\n", .{});
        return 2;
    }
    const project = try build.orchestrator.loadProject(ctx.allocator);
    var any = false;
    for (project.targets) |target| {
        for (target.sources) |pattern| {
            const sources = try build.orchestrator.resolveSourcePattern(ctx.allocator, pattern);
            for (sources) |source| {
                const code = try core.exec.runInherit(&.{ "clang-format", "-i", source });
                if (code != 0) return code;
                any = true;
            }
        }
    }
    if (!any) {
        try ctx.print("fmt: no source files found\n", .{});
    } else {
        try ctx.print("fmt: formatted project sources\n", .{});
    }
    return 0;
}

pub fn handleLint(ctx: *Context, command_args: []const []const u8) !u8 {
    ensureNoArgs(ctx, "lint", command_args) catch return 2;
    const project = try build.orchestrator.loadProject(ctx.allocator);
    if (core.exec.commandExists("clang-tidy")) {
        return runClangTidyLint(ctx, project);
    }

    const fallback = detectLintFallback() orelse {
        try ctx.printErr("error: clang-tidy not found and no fallback compiler available\n", .{});
        return 2;
    };
    try ctx.print("lint: clang-tidy missing; running syntax-only checks with {s}\n", .{fallback.label});
    return runFallbackLint(ctx, project, fallback);
}

const LintFallback = struct {
    label: []const u8,
    command_prefix: []const []const u8,
};

fn detectLintFallback() ?LintFallback {
    if (core.exec.commandExists("clang++")) {
        return .{
            .label = "clang++",
            .command_prefix = &.{"clang++"},
        };
    }
    if (core.exec.commandExists("g++")) {
        return .{
            .label = "g++",
            .command_prefix = &.{"g++"},
        };
    }
    if (core.exec.commandExists("zig")) {
        return .{
            .label = "zig c++",
            .command_prefix = &.{ "zig", "c++" },
        };
    }
    return null;
}

fn runClangTidyLint(ctx: *Context, project: project_mod.Project) !u8 {
    var any = false;
    for (project.targets) |target| {
        for (target.sources) |pattern| {
            const sources = try build.orchestrator.resolveSourcePattern(ctx.allocator, pattern);
            for (sources) |source| {
                var argv: std.ArrayList([]const u8) = .empty;
                defer argv.deinit(ctx.allocator);
                try argv.append(ctx.allocator, "clang-tidy");
                try argv.append(ctx.allocator, source);
                try argv.append(ctx.allocator, "--");
                try appendLintCompilerArgs(
                    ctx.allocator,
                    &argv,
                    project.defaults.cpp_standard,
                    target.include_dirs,
                    target.defines,
                    target.cflags,
                );

                const code = try core.exec.runInherit(argv.items);
                if (code != 0) return code;
                any = true;
            }
        }
    }
    if (!any) {
        try ctx.print("lint: no source files found\n", .{});
    } else {
        try ctx.print("lint: linted project sources\n", .{});
    }
    return 0;
}

fn runFallbackLint(ctx: *Context, project: project_mod.Project, fallback: LintFallback) !u8 {
    var any = false;
    for (project.targets) |target| {
        for (target.sources) |pattern| {
            const sources = try build.orchestrator.resolveSourcePattern(ctx.allocator, pattern);
            for (sources) |source| {
                var argv: std.ArrayList([]const u8) = .empty;
                defer argv.deinit(ctx.allocator);

                for (fallback.command_prefix) |arg| {
                    try argv.append(ctx.allocator, arg);
                }
                try argv.append(ctx.allocator, "-fsyntax-only");
                try appendLintCompilerArgs(
                    ctx.allocator,
                    &argv,
                    project.defaults.cpp_standard,
                    target.include_dirs,
                    target.defines,
                    target.cflags,
                );
                try argv.append(ctx.allocator, source);

                const code = try core.exec.runInherit(argv.items);
                if (code != 0) return code;
                any = true;
            }
        }
    }
    if (!any) {
        try ctx.print("lint: no source files found\n", .{});
    } else {
        try ctx.print("lint: linted project sources (fallback)\n", .{});
    }
    return 0;
}

fn appendLintCompilerArgs(
    allocator: std.mem.Allocator,
    argv: *std.ArrayList([]const u8),
    standard: project_mod.CppStandard,
    include_dirs: []const []const u8,
    defines: []const []const u8,
    cflags: []const []const u8,
) !void {
    try argv.append(allocator, lintStandardFlag(standard));
    for (include_dirs) |include_dir| {
        try argv.append(allocator, try std.fmt.allocPrint(allocator, "-I{s}", .{include_dir}));
    }
    for (defines) |define| {
        try argv.append(allocator, try std.fmt.allocPrint(allocator, "-D{s}", .{define}));
    }
    for (cflags) |flag| {
        try argv.append(allocator, flag);
    }
}

fn lintStandardFlag(standard: project_mod.CppStandard) []const u8 {
    return switch (standard) {
        .c89 => "-std=c89",
        .c99 => "-std=c99",
        .c11 => "-std=c11",
        .c17 => "-std=c17",
        .cpp11 => "-std=c++11",
        .cpp14 => "-std=c++14",
        .cpp17 => "-std=c++17",
        .cpp20 => "-std=c++20",
        .cpp23 => "-std=c++23",
    };
}

pub fn handleInfo(ctx: *Context, command_args: []const []const u8) !u8 {
    ensureNoArgs(ctx, "info", command_args) catch return 2;
    const project = try build.orchestrator.loadProject(ctx.allocator);
    try ctx.print("project: {s}\n", .{project.name});
    try ctx.print("version: {s}\n", .{project.version});
    try ctx.print("license: {s}\n", .{project.license orelse "n/a"});
    try ctx.print("schema: {s}\n", .{project.ovo_schema});
    try ctx.print("targets: {d}\n", .{project.targets.len});
    try ctx.print("dependencies: {d}\n", .{project.dependencies.len});
    try ctx.print("backend: {s}\n", .{project.defaults.backend});
    try ctx.print("optimize: {s}\n", .{project.defaults.optimize});
    try ctx.print("output_dir: {s}\n", .{project.defaults.output_dir});
    if (project.targets.len > 0) {
        try ctx.print("target_list:\n", .{});
        for (project.targets) |target| {
            try ctx.print("  - {s} ({s})\n", .{ target.name, project_mod.targetTypeLabel(target.kind) });
        }
    }
    if (project.dependencies.len > 0) {
        try ctx.print("dependency_list:\n", .{});
        for (project.dependencies) |dep| {
            try ctx.print("  - {s}@{s}\n", .{ dep.name, dep.version });
        }
    }
    return 0;
}

pub fn handleTree(ctx: *Context, command_args: []const []const u8) !u8 {
    var format: graph.renderer.TreeFormat = .ascii;
    var target_filter: ?[]const u8 = null;

    for (command_args) |arg| {
        if (std.mem.startsWith(u8, arg, "--format=")) {
            const value = arg["--format=".len..];
            format = graph.renderer.parseTreeFormat(value) orelse {
                try ctx.printErr("error: unsupported tree format '{s}'\n", .{value});
                return 2;
            };
        } else if (std.mem.startsWith(u8, arg, "--target=")) {
            target_filter = arg["--target=".len..];
        }
    }

    const project = try build.orchestrator.loadProject(ctx.allocator);
    const output = try graph.renderer.renderTree(ctx.allocator, project, format, target_filter);
    try ctx.print("{s}", .{output});
    return 0;
}

pub fn handleImport(ctx: *Context, command_args: []const []const u8) !u8 {
    if (command_args.len == 0) {
        try ctx.printErr("error: missing import format\n", .{});
        return 2;
    }
    const format = translate.importer.parseImportFormat(command_args[0]) orelse {
        try ctx.printErr("error: unsupported import format '{s}'\n", .{command_args[0]});
        return 2;
    };
    const source_path = if (command_args.len > 1) command_args[1] else ".";
    const imported = try translate.importer.importIntoBuildZon(ctx.allocator, format, source_path);
    if (core.fs.fileExists("build.zon")) {
        try core.fs.copyFile(ctx.allocator, "build.zon", "build.zon.bak");
    }
    try translate.importer.writeImportedProject(ctx.allocator, imported);
    try ctx.print("import: converted {s} -> build.zon\n", .{translate.importer.label(format)});
    return 0;
}

pub fn handleExport(ctx: *Context, command_args: []const []const u8) !u8 {
    if (command_args.len == 0) {
        try ctx.printErr("error: missing export format\n", .{});
        return 2;
    }
    const format = translate.exporter.parseExportFormat(command_args[0]) orelse {
        try ctx.printErr("error: unsupported export format '{s}'\n", .{command_args[0]});
        return 2;
    };
    const project = try build.orchestrator.loadProject(ctx.allocator);
    const content = try translate.exporter.exportProject(ctx.allocator, project, format);
    const output_path = if (command_args.len > 1)
        command_args[1]
    else
        try translate.exporter.defaultPathForFormat(ctx.allocator, project, format);
    try translate.exporter.writeExport(output_path, content);
    try ctx.print("export: wrote {s}\n", .{output_path});
    return 0;
}

fn projectNameFromCwd(allocator: std.mem.Allocator) []const u8 {
    const cwd = core.fs.currentPathAlloc(allocator) catch return "app";
    return projectDisplayNameFromPath(cwd);
}

fn validateNewProjectPath(path: []const u8) ProjectPathValidationError!void {
    if (path.len == 0) return ProjectPathValidationError.EmptyPath;
    if (std.fs.path.isAbsolute(path)) return ProjectPathValidationError.AbsolutePath;

    var component_iter = std.mem.tokenizeAny(u8, path, "/\\");
    var saw_component = false;
    while (component_iter.next()) |component| {
        saw_component = true;
        if (std.mem.eql(u8, component, ".")) return ProjectPathValidationError.CurrentDirectorySegment;
        if (std.mem.eql(u8, component, "..")) return ProjectPathValidationError.TraversalSegment;
    }

    if (!saw_component) return ProjectPathValidationError.EmptyPath;
}

fn projectDisplayNameFromPath(path: []const u8) []const u8 {
    const base = std.fs.path.basename(path);
    if (base.len == 0) return "app";
    if (std.mem.eql(u8, base, ".") or std.mem.eql(u8, base, "..")) return "app";
    for (base) |c| {
        if (c == '/' or c == '\\') return "app";
    }
    return base;
}

fn normalizeTargetBaseId(allocator: std.mem.Allocator, project_name: []const u8) ![]const u8 {
    var out: std.ArrayList(u8) = .empty;
    defer out.deinit(allocator);

    var last_sep = false;
    for (project_name) |c| {
        if (std.ascii.isAlphanumeric(c)) {
            try out.append(allocator, std.ascii.toLower(c));
            last_sep = false;
            continue;
        }

        if (out.items.len > 0 and !last_sep) {
            try out.append(allocator, '_');
            last_sep = true;
        }
    }

    while (out.items.len > 0 and out.items[out.items.len - 1] == '_') {
        _ = out.pop();
    }

    if (out.items.len == 0) {
        try out.appendSlice(allocator, "app");
    }

    if (std.ascii.isDigit(out.items[0])) {
        return try std.fmt.allocPrint(allocator, "app_{s}", .{out.items});
    }

    return try allocator.dupe(u8, out.items);
}
