const std = @import("std");
const Context = @import("context.zig").Context;
const scaffold = @import("scaffold.zig");
const core = @import("../core/mod.zig");
const project_mod = @import("../core/project.zig");
const build = @import("../build/mod.zig");
const package = @import("../package/mod.zig");
const translate = @import("../translate/mod.zig");
const graph = @import("../graph/mod.zig");

pub fn handleNew(ctx: *Context, command_args: []const []const u8) !u8 {
    if (command_args.len == 0) {
        try ctx.printErr("error: missing project name\n", .{});
        return 2;
    }
    const name = command_args[0];
    try scaffold.createProjectSkeleton(ctx.allocator, name, name);
    try core.fs.writeFile(
        try std.fmt.allocPrint(ctx.allocator, "{s}/README.md", .{name}),
        "Generated by OVO\n",
    );
    try ctx.print("new: created project '{s}'\n", .{name});
    return 0;
}

pub fn handleInit(ctx: *Context, _: []const []const u8) !u8 {
    const cwd_name = projectNameFromCwd(ctx.allocator);
    try scaffold.createProjectSkeleton(ctx.allocator, ".", cwd_name);
    try ctx.print("init: wrote build.zon and starter C++ layout for '{s}'\n", .{cwd_name});
    return 0;
}

pub fn handleBuild(ctx: *Context, command_args: []const []const u8, _: []const []const u8) !u8 {
    var force = false;
    var target_name: ?[]const u8 = null;
    for (command_args) |arg| {
        if (std.mem.eql(u8, arg, "--force")) {
            force = true;
        } else if (std.mem.startsWith(u8, arg, "--")) {
            try ctx.printErr("error: unknown build flag '{s}'\n", .{arg});
            return 2;
        } else if (target_name == null) {
            target_name = arg;
        }
    }
    const result = try build.orchestrator.buildProject(ctx.allocator, .{
        .target_name = target_name,
        .optimize_override = ctx.profile,
        .force = force,
    });
    try ctx.print("build: project={s}\n", .{result.project_name});
    for (result.artifacts) |artifact| {
        try ctx.print("  built {s} -> {s}\n", .{ artifact.name, artifact.path });
    }
    return 0;
}

pub fn handleRun(ctx: *Context, command_args: []const []const u8, passthrough_args: []const []const u8) !u8 {
    var requested_target = if (command_args.len > 0) command_args[0] else null;
    if (requested_target == null) {
        const project = try build.orchestrator.loadProject(ctx.allocator);
        const target = build.orchestrator.defaultRunnableTarget(project) orelse {
            try ctx.printErr("error: no executable or test target available\n", .{});
            return 2;
        };
        requested_target = target.name;
    }

    const result = try build.orchestrator.buildProject(ctx.allocator, .{
        .target_name = requested_target,
        .optimize_override = ctx.profile,
    });
    const artifact = build.orchestrator.findRunnableArtifact(result, requested_target) orelse {
        try ctx.printErr("error: no runnable executable target found\n", .{});
        return 2;
    };

    var argv: std.ArrayList([]const u8) = .empty;
    try argv.append(ctx.allocator, artifact.path);
    for (passthrough_args) |arg| try argv.append(ctx.allocator, arg);
    const code = try core.exec.runInherit(ctx.allocator, argv.items);
    return code;
}

pub fn handleTest(ctx: *Context, command_args: []const []const u8, _: []const []const u8) !u8 {
    const pattern = if (command_args.len > 0) command_args[0] else null;
    const result = try build.orchestrator.buildProject(ctx.allocator, .{
        .target_pattern = pattern,
        .optimize_override = ctx.profile,
        .test_only = true,
    });

    for (result.artifacts) |artifact| {
        var argv: std.ArrayList([]const u8) = .empty;
        try argv.append(ctx.allocator, artifact.path);
        const code = try core.exec.runInherit(ctx.allocator, argv.items);
        if (code != 0) return code;
    }
    try ctx.print("test: executed {d} test target(s)\n", .{result.artifacts.len});
    return 0;
}

pub fn handleClean(ctx: *Context, _: []const []const u8) !u8 {
    try core.fs.removeTreeIfExists(".ovo");
    try core.fs.deleteFileIfExists("ovo.lock.zon");
    try ctx.print("clean: removed .ovo and transient lock artifacts\n", .{});
    return 0;
}

pub fn handleInstall(ctx: *Context, _: []const []const u8) !u8 {
    const result = try build.orchestrator.buildProject(ctx.allocator, .{
        .optimize_override = ctx.profile,
    });
    try core.fs.ensureDir(".ovo/install/bin");
    try core.fs.ensureDir(".ovo/install/lib");

    for (result.artifacts) |artifact| {
        const file_name = std.fs.path.basename(artifact.path);
        const install_path = switch (artifact.kind) {
            .executable, .test_target => try std.fmt.allocPrint(ctx.allocator, ".ovo/install/bin/{s}", .{file_name}),
            .library_static, .library_shared => try std.fmt.allocPrint(ctx.allocator, ".ovo/install/lib/{s}", .{file_name}),
        };
        defer ctx.allocator.free(install_path);

        try core.fs.copyFile(ctx.allocator, artifact.path, install_path);
        try ctx.print("install: {s}\n", .{install_path});
    }
    return 0;
}

pub fn handleAdd(ctx: *Context, command_args: []const []const u8) !u8 {
    if (command_args.len == 0) {
        try ctx.printErr("error: missing package name\n", .{});
        return 2;
    }
    var manager = package.manager.PackageManager.init(ctx.allocator);
    const version = if (command_args.len > 1) command_args[1] else null;
    try manager.add(command_args[0], version);
    try ctx.print("add: {s}\n", .{command_args[0]});
    return 0;
}

pub fn handleRemove(ctx: *Context, command_args: []const []const u8) !u8 {
    if (command_args.len == 0) {
        try ctx.printErr("error: missing package name\n", .{});
        return 2;
    }
    var manager = package.manager.PackageManager.init(ctx.allocator);
    try manager.remove(command_args[0]);
    try ctx.print("remove: {s}\n", .{command_args[0]});
    return 0;
}

pub fn handleFetch(ctx: *Context, _: []const []const u8) !u8 {
    const project = try build.orchestrator.loadProject(ctx.allocator);
    var manager = package.manager.PackageManager.init(ctx.allocator);
    try manager.fetch();
    try ctx.print("fetch: dependency cache refreshed ({d} deps)\n", .{project.dependencies.len});
    return 0;
}

pub fn handleUpdate(ctx: *Context, command_args: []const []const u8) !u8 {
    var manager = package.manager.PackageManager.init(ctx.allocator);
    const dep = if (command_args.len > 0) command_args[0] else null;
    try manager.update(dep);
    if (dep) |name| {
        try ctx.print("update: dependency {s} updated\n", .{name});
    } else {
        try ctx.print("update: dependencies updated\n", .{});
    }
    return 0;
}

pub fn handleLock(ctx: *Context, _: []const []const u8) !u8 {
    var manager = package.manager.PackageManager.init(ctx.allocator);
    try manager.lock();
    try ctx.print("lock: wrote ovo.lock.zon\n", .{});
    return 0;
}

pub fn handleDeps(ctx: *Context, _: []const []const u8) !u8 {
    var manager = package.manager.PackageManager.init(ctx.allocator);
    const summary = try manager.dependencySummary();
    try ctx.print("{s}\n", .{summary});
    return 0;
}

pub fn handleDoc(ctx: *Context, _: []const []const u8) !u8 {
    const project = try build.orchestrator.loadProject(ctx.allocator);
    try core.fs.ensureDir("docs");
    var output: std.ArrayList(u8) = .empty;

    try output.print(ctx.allocator, "# {s}\n\n", .{project.name});
    try output.print(ctx.allocator, "- Version: `{s}`\n", .{project.version});
    try output.print(ctx.allocator, "- License: `{s}`\n", .{project.license orelse "n/a"});
    try output.print(ctx.allocator, "- Targets: `{d}`\n", .{project.targets.len});
    try output.print(ctx.allocator, "- Dependencies: `{d}`\n", .{project.dependencies.len});
    try output.appendSlice(ctx.allocator, "\n## Targets\n");
    for (project.targets) |target| {
        try output.print(ctx.allocator, "- `{s}` (`{s}`)\n", .{ target.name, project_mod.targetTypeLabel(target.kind) });
    }

    try core.fs.writeFile("docs/project-reference.md", output.items);
    try ctx.print("doc: wrote docs/project-reference.md\n", .{});
    return 0;
}

pub fn handleDoctor(ctx: *Context, _: []const []const u8) !u8 {
    const required_version_raw = core.fs.readFileAlloc(ctx.allocator, ".zigversion") catch null;
    const required_version: []const u8 = if (required_version_raw) |bytes|
        std.mem.trim(u8, bytes, " \t\r\n")
    else
        "0.16.0";
    try ctx.print("doctor: required_zig={s}\n", .{required_version});
    const zig_version_code = core.exec.runInherit(ctx.allocator, &.{ "zig", "version" }) catch 1;
    if (zig_version_code != 0) {
        try ctx.printErr("doctor: unable to run `zig version`\n", .{});
    }

    const ToolCheck = struct {
        name: []const u8,
        required: bool,
    };
    const tools = [_]ToolCheck{
        .{ .name = "zig", .required = true },
        .{ .name = "clang++", .required = false },
        .{ .name = "g++", .required = false },
        .{ .name = "cmake", .required = false },
        .{ .name = "ninja", .required = false },
        .{ .name = "clang-format", .required = false },
        .{ .name = "clang-tidy", .required = false },
        .{ .name = "doxygen", .required = false },
        .{ .name = "clang-doc", .required = false },
    };
    var missing_required: usize = 0;
    var missing_optional: usize = 0;
    for (tools) |tool| {
        const available = core.exec.commandExists(ctx.allocator, tool.name);
        if (available) {
            try ctx.print("doctor: {s} ok\n", .{tool.name});
            continue;
        }
        if (tool.required) {
            try ctx.print("doctor: {s} missing-required\n", .{tool.name});
            missing_required += 1;
        } else {
            try ctx.print("doctor: {s} missing-optional\n", .{tool.name});
            missing_optional += 1;
        }
    }
    if (missing_optional > 0) {
        try ctx.print("doctor: optional tools missing ({d}); related subcommands may use fallbacks\n", .{missing_optional});
    }
    return if (zig_version_code == 0 and missing_required == 0) 0 else 1;
}

pub fn handleFmt(ctx: *Context, _: []const []const u8) !u8 {
    if (!core.exec.commandExists(ctx.allocator, "clang-format")) {
        try ctx.printErr("error: clang-format not found in PATH\n", .{});
        return 2;
    }
    const project = try build.orchestrator.loadProject(ctx.allocator);
    var any = false;
    for (project.targets) |target| {
        for (target.sources) |pattern| {
            const sources = try build.orchestrator.resolveSourcePattern(ctx.allocator, pattern);
            for (sources) |source| {
                const code = try core.exec.runInherit(ctx.allocator, &.{ "clang-format", "-i", source });
                if (code != 0) return code;
                any = true;
            }
        }
    }
    if (!any) {
        try ctx.print("fmt: no source files found\n", .{});
    } else {
        try ctx.print("fmt: formatted project sources\n", .{});
    }
    return 0;
}

pub fn handleLint(ctx: *Context, _: []const []const u8) !u8 {
    const project = try build.orchestrator.loadProject(ctx.allocator);
    if (core.exec.commandExists(ctx.allocator, "clang-tidy")) {
        return runClangTidyLint(ctx, project);
    }

    const fallback = detectLintFallback(ctx.allocator) orelse {
        try ctx.printErr("error: clang-tidy not found and no fallback compiler available\n", .{});
        return 2;
    };
    try ctx.print("lint: clang-tidy missing; running syntax-only checks with {s}\n", .{fallback.label});
    return runFallbackLint(ctx, project, fallback);
}

const LintFallback = struct {
    label: []const u8,
    command_prefix: []const []const u8,
};

fn detectLintFallback(allocator: std.mem.Allocator) ?LintFallback {
    if (core.exec.commandExists(allocator, "clang++")) {
        return .{
            .label = "clang++",
            .command_prefix = &.{"clang++"},
        };
    }
    if (core.exec.commandExists(allocator, "g++")) {
        return .{
            .label = "g++",
            .command_prefix = &.{"g++"},
        };
    }
    if (core.exec.commandExists(allocator, "zig")) {
        return .{
            .label = "zig c++",
            .command_prefix = &.{ "zig", "c++" },
        };
    }
    return null;
}

fn runClangTidyLint(ctx: *Context, project: project_mod.Project) !u8 {
    var any = false;
    for (project.targets) |target| {
        for (target.sources) |pattern| {
            const sources = try build.orchestrator.resolveSourcePattern(ctx.allocator, pattern);
            for (sources) |source| {
                var argv: std.ArrayList([]const u8) = .empty;
                defer argv.deinit(ctx.allocator);
                try argv.append(ctx.allocator, "clang-tidy");
                try argv.append(ctx.allocator, source);
                try argv.append(ctx.allocator, "--");
                try appendLintCompilerArgs(
                    ctx.allocator,
                    &argv,
                    project.defaults.cpp_standard,
                    target.include_dirs,
                    target.defines,
                    target.cflags,
                );

                const code = try core.exec.runInherit(ctx.allocator, argv.items);
                if (code != 0) return code;
                any = true;
            }
        }
    }
    if (!any) {
        try ctx.print("lint: no source files found\n", .{});
    } else {
        try ctx.print("lint: linted project sources\n", .{});
    }
    return 0;
}

fn runFallbackLint(ctx: *Context, project: project_mod.Project, fallback: LintFallback) !u8 {
    var any = false;
    for (project.targets) |target| {
        for (target.sources) |pattern| {
            const sources = try build.orchestrator.resolveSourcePattern(ctx.allocator, pattern);
            for (sources) |source| {
                var argv: std.ArrayList([]const u8) = .empty;
                defer argv.deinit(ctx.allocator);

                for (fallback.command_prefix) |arg| {
                    try argv.append(ctx.allocator, arg);
                }
                try argv.append(ctx.allocator, "-fsyntax-only");
                try appendLintCompilerArgs(
                    ctx.allocator,
                    &argv,
                    project.defaults.cpp_standard,
                    target.include_dirs,
                    target.defines,
                    target.cflags,
                );
                try argv.append(ctx.allocator, source);

                const code = try core.exec.runInherit(ctx.allocator, argv.items);
                if (code != 0) return code;
                any = true;
            }
        }
    }
    if (!any) {
        try ctx.print("lint: no source files found\n", .{});
    } else {
        try ctx.print("lint: linted project sources (fallback)\n", .{});
    }
    return 0;
}

fn appendLintCompilerArgs(
    allocator: std.mem.Allocator,
    argv: *std.ArrayList([]const u8),
    standard: project_mod.CppStandard,
    include_dirs: []const []const u8,
    defines: []const []const u8,
    cflags: []const []const u8,
) !void {
    try argv.append(allocator, lintStandardFlag(standard));
    for (include_dirs) |include_dir| {
        try argv.append(allocator, try std.fmt.allocPrint(allocator, "-I{s}", .{include_dir}));
    }
    for (defines) |define| {
        try argv.append(allocator, try std.fmt.allocPrint(allocator, "-D{s}", .{define}));
    }
    for (cflags) |flag| {
        try argv.append(allocator, flag);
    }
}

fn lintStandardFlag(standard: project_mod.CppStandard) []const u8 {
    return switch (standard) {
        .c89 => "-std=c89",
        .c99 => "-std=c99",
        .c11 => "-std=c11",
        .c17 => "-std=c17",
        .cpp11 => "-std=c++11",
        .cpp14 => "-std=c++14",
        .cpp17 => "-std=c++17",
        .cpp20 => "-std=c++20",
        .cpp23 => "-std=c++23",
    };
}

pub fn handleInfo(ctx: *Context, _: []const []const u8) !u8 {
    const project = try build.orchestrator.loadProject(ctx.allocator);
    try ctx.print("project: {s}\n", .{project.name});
    try ctx.print("version: {s}\n", .{project.version});
    try ctx.print("license: {s}\n", .{project.license orelse "n/a"});
    try ctx.print("schema: {s}\n", .{project.ovo_schema});
    try ctx.print("targets: {d}\n", .{project.targets.len});
    try ctx.print("dependencies: {d}\n", .{project.dependencies.len});
    try ctx.print("backend: {s}\n", .{project.defaults.backend});
    try ctx.print("optimize: {s}\n", .{project.defaults.optimize});
    try ctx.print("output_dir: {s}\n", .{project.defaults.output_dir});
    if (project.targets.len > 0) {
        try ctx.print("target_list:\n", .{});
        for (project.targets) |target| {
            try ctx.print("  - {s} ({s})\n", .{ target.name, project_mod.targetTypeLabel(target.kind) });
        }
    }
    if (project.dependencies.len > 0) {
        try ctx.print("dependency_list:\n", .{});
        for (project.dependencies) |dep| {
            try ctx.print("  - {s}@{s}\n", .{ dep.name, dep.version });
        }
    }
    return 0;
}

pub fn handleTree(ctx: *Context, command_args: []const []const u8) !u8 {
    var format: graph.renderer.TreeFormat = .ascii;
    var target_filter: ?[]const u8 = null;

    for (command_args) |arg| {
        if (std.mem.startsWith(u8, arg, "--format=")) {
            const value = arg["--format=".len..];
            format = graph.renderer.parseTreeFormat(value) orelse {
                try ctx.printErr("error: unsupported tree format '{s}'\n", .{value});
                return 2;
            };
        } else if (std.mem.startsWith(u8, arg, "--target=")) {
            target_filter = arg["--target=".len..];
        }
    }

    const project = try build.orchestrator.loadProject(ctx.allocator);
    const output = try graph.renderer.renderTree(ctx.allocator, project, format, target_filter);
    try ctx.print("{s}", .{output});
    return 0;
}

pub fn handleImport(ctx: *Context, command_args: []const []const u8) !u8 {
    if (command_args.len == 0) {
        try ctx.printErr("error: missing import format\n", .{});
        return 2;
    }
    const format = translate.importer.parseImportFormat(command_args[0]) orelse {
        try ctx.printErr("error: unsupported import format '{s}'\n", .{command_args[0]});
        return 2;
    };
    const source_path = if (command_args.len > 1) command_args[1] else ".";
    const imported = try translate.importer.importIntoBuildZon(ctx.allocator, format, source_path);
    if (core.fs.fileExists("build.zon")) {
        try core.fs.copyFile(ctx.allocator, "build.zon", "build.zon.bak");
    }
    try translate.importer.writeImportedProject(ctx.allocator, imported);
    try ctx.print("import: converted {s} -> build.zon\n", .{translate.importer.label(format)});
    return 0;
}

pub fn handleExport(ctx: *Context, command_args: []const []const u8) !u8 {
    if (command_args.len == 0) {
        try ctx.printErr("error: missing export format\n", .{});
        return 2;
    }
    const format = translate.exporter.parseExportFormat(command_args[0]) orelse {
        try ctx.printErr("error: unsupported export format '{s}'\n", .{command_args[0]});
        return 2;
    };
    const project = try build.orchestrator.loadProject(ctx.allocator);
    const content = try translate.exporter.exportProject(ctx.allocator, project, format);
    const output_path = if (command_args.len > 1)
        command_args[1]
    else
        try translate.exporter.defaultPathForFormat(ctx.allocator, project, format);
    try translate.exporter.writeExport(output_path, content);
    try ctx.print("export: wrote {s}\n", .{output_path});
    return 0;
}

fn projectNameFromCwd(allocator: std.mem.Allocator) []const u8 {
    const cwd = core.fs.currentPathAlloc(allocator) catch return "app";
    return std.fs.path.basename(cwd);
}
